CATALOG_MERCHANTS = frozenset(
    {
        "7-Eleven",
        "99",
        "ALIEXPRESS",
        "AMC Theatres",
        "APPLE.COM/BILL",
        "Aerolíneas Argentinas",
        "Aeroméxico",
        "Avianca",
        "BINANCE.COM",
        "BOOKING.COM",
        "CVS Pharmacy",
        "Cabify",
        "Café Martínez",
        "Carrefour",
        "Cine Colombia",
        "Cinemark",
        "Cinemark Hoyts",
        "Cineplanet",
        "Cinépolis",
        "Claro",
        "Coto",
        "D1",
        "Delta Air Lines",
        "DiDi",
        "DoorDash",
        "Drogas La Rebaja",
        "Drogasil",
        "Falabella",
        "Farmacias Guadalajara",
        "Farmacity",
        "G2A.COM",
        "GOOGLE *PLAY",
        "Inkafarma",
        "Ipiranga",
        "Juan Valdez Café",
        "LATAM Airlines",
        "Liverpool",
        "Magazine Luiza",
        "Mercado Libre",
        "Movistar",
        "NORDVPN.COM",
        "Netflix",
        "OXXO",
        "Oxxo Brasil",
        "PAYPAL *EBAY",
        "PLAYSTATION NETWORK",
        "PedidosYa",
        "Pemex",
        "Personal",
        "Plaza Vea",
        "Primax",
        "Pão de Açúcar",
        "Rappi",
        "SHEIN.COM",
        "STEAMGAMES.COM",
        "Saga Falabella",
        "Shell",
        "Starbucks",
        "TEMU.COM",
        "Tambo+",
        "Target",
        "Telcel",
        "Terpel",
        "Uber",
        "Verizon",
        "Vivo",
        "Walmart Supercenter",
        "Whole Foods Market",
        "YPF",
        "iFood",
        "Éxito",
    }
)

COMMON_WORD_MERCHANTS = frozenset({"Claro", "Éxito", "Vivo", "Personal", "Target", "Shell"})
